# 内置资源站列表
BUILTIN_SOURCES = [
    ("360资源站", "https://360zy.com/api.php/provide/vod/", "影视"),
    ("鸭鸭资源站", "https://cj.yayazy.net/api.php/provide/vod/", "影视"),
    ("光速资源站", "https://api.guangsuapi.com/api.php/provide/vod/", "影视"),
    ("天涯影视资源站", "https://tyyszyapi.com/api.php/provide/vod/", "影视"),
    ("豪华资源站", "https://haohuazy.com/api.php/provide/vod/", "影视"),
    ("新极品资源站", "https://jipinvip1.com/api.php/provide/vod/", "影视"),
    ("无尽资源站", "https://api.wujinapi.me/api.php/provide/vod/", "影视"),
    ("暴风资源站", "https://bfzyapi.com/api.php/provide/vod/", "影视"),
    ("最大资源站", "http://zuidazy.me/api.php/provide/vod/", "影视"),
    ("极速资源站", "https://jszyapi.com/api.php/provide/vod/", "影视"),
    ("爱奇艺资源站", "https://iqiyizyapi.com/api.php/provide/vod", "影视"),
    ("牛牛资源", "https://api.niuniuzy.me/api.php/provide/vod/", "影视"),
    ("索尼采集站", "https://suonizy.net/api.php/provide/vod/", "影视"),
    ("红牛资源站", "http://hongniuzy2.com/api.php/provide/vod/", "影视"),
    ("茅台资源站", "https://mtzy5.com/api.php/provide/vod/", "影视"),
    ("虎牙资源站", "https://huyazy.net/api.php/provide/vod/", "影视"),
    ("豆瓣资源站", "https://dbzy.tv/api.php/provide/vod/", "影视"),
    ("速播资源站", "https://subocj.com/api.php/provide/vod/", "影视"),
    ("速播资源站2", "https://www.suboziyuan.net/api.php/provide/vod/", "影视"),
    ("金鹰资源站", "https://jyzyapi.com/provide/vod/", "影视"),
    ("155资源站", "https://155api.com/api.php/provide/vod", "影视"),
    ("非凡资源站", "https://ffzy5.tv/api.php/provide/vod/", "影视"),
    ("飘零影院资源站", "https://p2100.net/api.php/provide/vod/", "影视"),
    ("JKUN资源站", "https://jkunzyapi.com/api.php/provide/vod", "影视"),
    ("魔都资源站", "https://www.mdzyapi.com/api.php/provide/vod/", "影视"),
    ("乐播资源站", "https://lbapi9.com/api.php/provide/vod/", "影视"),
    ("大地资源站", "https://dadiapi.com/api.php", "影视"),
    ("爱坤资源站", "https://ikunzyapi.com/api.php/provide/vod/", "影视"),
    ("大X子资源站", "https://apidanaizi.com/api.php/provide/vod/", "影视"),
    ("奥斯卡资源站", "https://aosikazy.com/api.php/provide/vod/", "影视"),
    ("奶香香资源站", "https://naixxzy.com/api.php/provide/vod/", "影视"),
    ("小鸡资源站", "https://api.xiaojizy.live/provide/vod/", "影视"),
    ("桃花资源站", "https://thzy1.me/api.php/provide/vod/", "影视"),
    ("森林资源站", "https://slapibf.com/api.php/provide/vod/", "影视"),
    ("樱花资源站", "https://m3u8.apiyhzy.com/api.php/provide/vod", "影视"),
    ("湿乐园资源站", "https://xxavs.com/api.php/provide/vod/", "影视"),
    ("滴滴资源站", "https://api.ddapi.cc/api.php/provide/vod/", "影视"),
    ("玉兔资源站", "https://apiyutu.com/api.php/provide/vod/", "影视"),
    ("番号资源站", "http://fhapi9.com/api.php/provide/vod/", "影视"),
    ("番茄资源站", "https://fqzy.me/api.php/provide/vod/", "影视"),
    ("百花资源站", "https://bhziyuan.com/api.php/provide/vod", "影视"),
    ("精品X资源站", "https://www.jingpinx.com/api.php/provide/vod", "影视"),
    ("细胞网资源站", "https://www.xxibaozyw.com/api.php/provide/vod", "影视"),
    ("老色X资源站", "https://apilsbzy1.com/api.php/provide/vod/", "影视"),
    ("色猫资源站", "https://caiji.semaozy.net/inc/api.php", "影视"),
    ("越南资源站", "https://api.vnzyz.com/api.php/provide/vod/", "影视"),
    ("辣椒资源站", "https://apilj.com/api.php/provide/vod/", "影视"),
    ("香蕉资源站", "https://www.xiangjiaozyw.com/api.php/provide/vod/", "影视"),
    ("鲨鱼资源站", "https://shayuapi.com/api.php/provide/vod/", "影视"),
    ("麻豆资源站", "https://91md.me/api.php/provide/vod/", "影视"),
    ("X色仓库资源", "https://hsckzy888.com/api.php/provide/vod", "影视"),
    ("黑料资源站", "https://heiliaozyapi.com/api.php/provide/vod/", "影视"),
    ("ok资源站", "https://api.okzy.com/api.php/provide/vod", "影视"),
    ("u酷资源站", "https://api.ukuzy.com/api.php/provide/vod/", "影视"),
    ("优质资源站", "https://api.yzzy.com/api.php/provide/vod/", "影视"),
    ("如意资源站", "https://api.ryzy.com/api.php/provide/vod/", "影视"),
    ("快车资源站", "https://api.kczy.com/api.php/provide/vod/", "影视"),
    ("新浪资源站", "https://api.xlzy.com/api.php/provide/vod/", "影视"),
    ("红牛资源站2", "https://api.hnzy2.com/api.php/provide/vod/", "影视"),
    ("闪电资源", "https://api.sdzy.com/api.php/provide/vod/", "影视"),
    ("雅集资源站", "https://api.yjzy.com/api.php/provide/vod/", "影视"),
    ("ck资源站", "https://api.ckzy.com/api.php/provide/vod/", "影视"),
    ("百度云资源站", "https://api.apibdzy.com/api.php/provide/vod/", "影视"),
    ("艾旦资源站", "https://lovedan.net/api.php/provide/vod/", "影视"),
    ("搜A-V资源站", "https://api.souavzyw.net/api.php/provide/vod/", "影视"),
    ("白嫖资源站", "https://www.kxgav.com/api/json.php", "影视"),
    ("美少女资源站", "https://www.msnii.com/api/json.php", "影视"),
    ("豆豆资源站", "https://api.douapi.cc/api.php/provide/vod", "影视"),
    ("X色A-V资源站", "https://www.pgxdy.com/api/json.php", "影视"),
    ("清水源资源站", "https://www.xrbsp.com/api/json.php", "影视"),
    ("香系源资源站", "https://www.gdlsp.com/api/json.php", "影视"),
]

def get_builtin_resources():
    """返回内置资源站列表"""
    resources = []
    for name, link, category in BUILTIN_SOURCES:
        resources.append({
            "name": name,
            "link": link.rstrip('/'),
            "description": f"{name}，分类: {category}",
            "status": "未知",
            "uptime": "-",
            "resource_count": "-",
        })
    return resources
